### ISSUE TITLE
Kursutveckling vt18 lp4

### ISSUE THREAD

**Issue by emilfolino** [dbwebb-se/webapp#12]
Tankar och idéer i samband med kurstillfället i vt18 lp4.

**Comment by emilfolino** [comment]
Vissa av artiklarna hade kunnat genomarbetas lite mer då det känns som att de hoppar över smådelar lite här och där som gör att man får ta avbrott från artikeln för att hitta vad det är man missat och försöka lösa det på egen hand.

**Comment by emilfolino** [comment]
Jag tyckte projekt var helt okej det var väldigt bra man kände att man fick använda det mesta man lärt sig från tidigare kursmoment. Det ända jag var lite förvirrad över är väl kraven offline läge och native design. Jag förstår inte direkt varför dessa inte var implementerade som kursmoment jag vet ni visade hur man skapade båda dessa under genomgångar men jag undrar bara varför man inte hade de som kursmoment. Det är liksom superbra om man kan alla krav och har testat de innan man kommer in i ett projekt för man känner sig säker och man behöver inte läsa runt massa på google för att hitta rätt lösningar och förstå saker som man inte har läst om tidigare. Det är bara ett förslag fram över när ni gör projekt att se till att alla kraven är något man har gjort i tidigare kmom och inte bara något som ni har gått igenom för under kmom är det väldigt svårt att experimentera runt för man har inte så mycket tid kvar när man har två kurser samtidigt och man verkligen sätter sig in i att försöka sig lära sig allt genom praktik och även läsa. Det är mer kul om man får leka med koden och har tid att testa grejer man lär sig så mycket mer.

**Comment by emilfolino** [comment]
Kommentar till kursvärderingen: 

Tack för den värdefulla feedbacken och kommentarer om kursen.

Ni som studenter verkar allmänt nöjda med kursen i helhet och med tanke på att det är första gången kursen går i denna tappning hade det förväntats fler hårda kanter.

Vi i lärarteamet tar till oss kommentarer om mer cachning av data och hur man kan arbeta på detta sättet både som ren webapp och som hybrid app med Cordova. Ett större fokus på att utnyttja plugins och tekniker i Cordova har också varit inne över planeringen inför kommande kurstillfällen.

Inför det nyss avklarade kurstillfället spelades in nya videon till de flesta delarna av kursen. Det är tanken att dessa kompletteras av mer videomaterial inför kommande kurstillfällen. 

Lärarteamet funderar på hur vi kan fokusera på ytterligare JavaScript-ramverk i kursen. Detta kan bidra till ytterligare möjligheter för reflektion om val av teknik.

**Comment by mosbth** [comment]
Länk till kursutvärdering i sin helhet, inkl fritextsvar.
http://bfm.bth.se/public/rapport/5b1aadb9-3f47-4f08-8403-0006bd62de32

Svarsfrekvens 16/(35+22) och snittbetyg 3.69.

**Comment by emilfolino** [comment]
Lägg till ett inslag av funktionell programmering i samband med mithril och `map`, `filter`, `reduce`

**Comment by emilfolino** [comment]
Avslutar denna och fortsätter i #20
