### ISSUE TITLE
AF-lista gives error on reload page

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/webapp#3]
http://www.student.bth.se/~mosstud/dbwebb-kurser/webapp/example/ajax/index.min.html

> Hittat en grej till i exempelprogrammet. Om man tar fram af-statistiken på länsnivå, och i det läget försöker ladda om sidan, så funkar det inte. (TypeError: soklistaLan is null)

**Comment by emilfolino** [comment]
Exempelprogrammet används inte längre.
