### ISSUE TITLE
Verifiera att .dbwebb.tests inkluderar de tester som kan/bör göras

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/webapp#6]
Stäm av vilka tester som görs i `.dwbebb.map`. 

Städa bort gamla saker och lägg dit nya tester som behövs.

Notera om det är tester som vi inte gör, men borde göra.

**Comment by emilfolino** [comment]
Borde vi göra testar av npm install --save webpack|webpack-cli|mithril?

Testar av att cordova kan skapa rätt filstruktur som vi förväntar oss?

**Comment by emilfolino** [comment]
Uppdaterade tester för v3
